export const usePerfil = () => {
  const perfil = {
    intro: `A través de la empatía, honestidad, disciplina y compromiso es posible lograr una comunicación activa con los clientes y colaboradores para alcanzar los objetivos de los proyectos. \n \n En el año 2014, el sitio web diseñado para el  Banco del Libro fue seleccionado para participar en la Bienal Iberoamericana de Diseño BID. Del año 2013 al 2015 participé en el diseño y desarrollo del sitio web para el congreso Caracas Design.`,
    formacion: {
      titulo: `Formación`,
      texto: `Mis primeros estudios relacionados con la comunicación visual los realicé en la **Escuela de Fotografía** de **Roberto Mata en 2006**; aquí aprendí de fotografía documental: Revelado de películas en el laboratorio, técnicas de composición e iluminación. Ese mismo año, comencé a estudiar diseño gráfico en el **Instituto de Diseño Darias.** Meses después, tomé el primer curso de desarrollo web al aprender **Macromedia Flash 8** en **Posa Studio Creativo.** \n \n Después de completar el curso Flash, el paso natural fue aprender sobre HTML y CSS. Es por eso que completé un curso básico en ambas tecnologías en **Benllisoft en 2007**. Me gradué del I**nstituto de Diseño Darias en 2013**, donde aprendí los fundamentos del diseño visual, la tipografía, la ilustración, la identidad gráfica, la fotografía, entre otras cosas.\n \n En agosto de **2016**, tomé un **Taller de tipografía** en el Instituto Darias. En septiembre de ese mismo año, completé un curso de **Gestión de proyectos web** en la **Escuela web**. Terminé el año haciendo un **Taller de creación de marcas** en noviembre. A principios de **2019**, finalicé el **Front-End Developer Nanodegree** program en **Udacity.** \n \n Actualmente, estoy cursando **Foundations of User Experience (UX) Design** en Coursera. Mi objetivo es mejorar mis conocimientos y el enfoque en el proceso de desarrollo de aplicaciones web orientado en los usuarios.`,

      lista: `| Insituto de Diseño Darias |\n | :--- |\n | *Julio 2006 - mayo 2013* |\n | Diseñador Gráfico mención Comunicación Visual |\n | Udacity |\n | :--- |\n | *Enero 2019* |\n | Front-end Web Developer Nanodegree |\n | Instituto de Diseño Darias |\n | :--- |\n | *Agosto 2016 - noviembre 2016* |\n | Taller de tipografía, creación de alfabeto. Taller creación de marcas |\n | Escuela web |\n | :--- |\n | *Septiembre 2016* |\n | Gerencia de proyectos web |\n | Benllisoft |\n | :--- |\n | *Agosto 2007* |\n | HTML/CSS |\n | Posa studio creativo |\n | :--- |\n | *Mayo 2006* |\n | Macromedia Flash 8 |\n | Roberto Mata escuela de fotografía |\n | :--- |\n | *Junio 2006 - octubre 2006* |\n | Fotografía documental |`,
    },

    experiencia: {
      titulo: `Experiencia`,
      texto: `En el año **2005**, se suponía que iba a trabajar con dispositivos de voz sobre IP en el área de **soporte técnico**. El modelo de negocio no funcionaba porque las ofertas de software que ya existían eran gratuitas. Mi jefe en ese momento sabía de mi interés en el **diseño gráfico** y me propuso darle una oportunidad al **diseñar** algunos **impresos** y mi primer **sitio web.**\n \n A principios de **2006**, vi la oportunidad de fundar mi propia compañía y comencé a obtener algunos clientes, pero después de un año de trabajo, mi falta de conocimiento y experiencia me hizo darme cuenta de que necesitaba estudiar **comunicación visual** si quería tener éxito. En **2007**, mientras estudiaba en el **Instituto de Diseño Darias**, pude conocer al director de la escuela y nos hicimos amigos. El director me dio la oportunidad de trabajar como su **asistente** manteniendo el **sitio web** del instituto y participando en la preparación de la **Bienal de Tipos Latinos 2008.**\n \n En febrero de **2008,** obtuve mi primer trabajo relacionado con la **tecnología web** en los **Cursos Gerenciales**. Mis responsabilidades aquí fueron diseñar e **implementar en HTML/CSS** para **CMS basados ​​en PHP** y diseñar e implementar **Correos HTML**. Dejé el trabajo en Cursos Gerenciales porque tuve la oportunidad de trabajar con la agencia **BTL G2** con el objetivo de obtener más experiencia en las comunicaciones visuales. La realidad era muy diferente porque el trabajo consistía solo en la preparación de archivos de diseño de impresión.\n \n Pasé la segunda mitad de 2009, organizando la reactivación de la compañía que había fundado 3 años antes. **En enero de 2010**, comencé a trabajar como **Director creativo y Gerente de proyectos** web en Novanet; responsabilidades que desempeño hasta la fecha.`,

      lista: `| Novanet Studio |\n | :--- |\n | *Enero 2010 - presente* |\n | **Director - Creativo multimedia**|\n | Director creativo, gerente de proyectos web, diseño UI, diseño e implementación de identidades visuales |\n | Cursos Gerenciales |\n | :--- |\n | *Julio 2008 - febrero 2009* |\n | **Diseñador gráfico** |\n | Diseño web, maquetación html/css, mailing html, boletines web, gestores de contenido |\n | Instituto de Diseño Darias |\n | :--- |\n | *Febrero 2008 - agosto 2008* |\n | **Asistente de Dirección Académica** |\n | Diseño web, arte final, asistencia en montaje de exposiciones |\n | Grupo Novanet, C.A \n | :--- |\n | *Mayo 2006 - febrero 2007* |\n | **Diseñador gráfico junior** |\n | Diseñador web (programación y ensamblaje). Presentaciones multimedia. Piezas publicitarias impresas |\n | Representaciones Kotel, C.A. |\n | :--- |\n | *Marzo 2005 - mayo 2006* |\n | **Diseñador gráfico** |\n | Diseño imagen corporativa, papelería comercial. Piezas publicitarias: dípticos, volantes. Desarrollo de página web. |`,
    },
  };

  return perfil;
};
